#!/bin/bash

source "$(dirname "${BASH_SOURCE}")/imosh" || exit 1

rsync -az --delete -e "ssh -i ${HOME}/.ssh/ec2-tokyo.pem" ./ "ec2-user@${REMOTE_HOST}":~/ninefx

commands=(./run "$@")
func::array_map commands INPLACE func::escapeshellarg
ssh -i "${HOME}/.ssh/ec2-tokyo.pem" "ec2-user@${REMOTE_HOST}" -- "cd ninefx; ${commands[*]}"
